services:
  devices-api:
    build: .
    container_name: devices-api
    ports:
      - "8280:8280"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/devices_db
      - SPRING_DATASOURCE_USERNAME=devices_user
      - SPRING_DATASOURCE_PASSWORD=devices_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - devices-network
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    container_name: mysql-devices-db
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=devices_db
      - MYSQL_USER=devices_user
      - MYSQL_PASSWORD=devices_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - devices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

networks:
  devices-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local